### ISSUE TITLE
Plugin is not working, if it placed in Project's Plugins dir.

### ISSUE THREAD

**Issue by KhArtNJava** [ue4plugins/VlcMedia#10]
Hello.
I have placed your plugin to the  Project's Plugins dir.
And it is not playing video and gets error
LogWmfMedia:Error: An unrecoverable error occured in the media session: 0xC00D36E6
Tested on UE 4.9 preview 3.

Repro steps: https://youtu.be/NeXP9Ah9F8Q
Project's sources: https://drive.google.com/file/d/0B1Fl0c3AhVDZUXg1c3J0YUpQWHc/view?usp=sharing
Log file: https://drive.google.com/file/d/0B1Fl0c3AhVDZR2xveW8zREFwU2M/view?usp=sharing

**Comment by KhArtNJava** [comment]
Solved by switching off all another Media plugins in project settings.

**Comment by gmpreussner** [comment]
Looks like the WMF plug-in handled your video file (or at least tried to and failed). Turning it off is the way to go.
