### ISSUE TITLE
4.10 4.11 cant play rtsp streaming

### ISSUE THREAD

**Issue by cl8017** [ue4plugins/VlcMedia#15]
Hi, i have some problem when i try to use this plugin to play rtsp streaming.

UE4 4.10.4  + Unreal Engine 4.10.1 Compatible Plugin + vlc-2.2.3-win64
cant identify rstp streaming url

UE4 4.11.0 Preview 7  + Unreal Engine 4.11 Compatible Plugin + vlc-2.2.3-win64 or vlc-3.0.0-git-20151220-0402
can identify and  play rtsp streaming  but no image and no sound.

did i use wrong VideoLAN Nightly Builds or other reasons ?
i use this "rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp“ for test.

**Comment by cl8017** [comment]
i use this "rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp“ for test.

**Comment by gmpreussner** [comment]
Hey, sorry for the delay. I didn't have time to look into this yet. I'm currently overhauling the entire Media Framework. I might be able to look into this over the weekend. Thanks for your patience!

**Comment by gmpreussner** [comment]
The video above will work in 4.13.
