### ISSUE TITLE
Video playing only on editor and open URL is not working on runtime

### ISSUE THREAD

**Issue by adigyran** [ue4plugins/VlcMedia#16]
I have blueprint that load video from local url, in editor it works perfectly (unless sound issues on first run) but in "Play in standalone game" video not working.
OpenURL in editor runtime, after new link not working at all or throws access violation

**Comment by gmpreussner** [comment]
Yeah, it seems that a bunch of stuff broke in 4.11, including packaging. I'm not yet sure what caused it, but I'm currently doing a big refactoring pass on the Media Framework and will look into packaging as well.

**Comment by KhArtNJava** [comment]
Thank you!

**Comment by adigyran** [comment]
4.12 master branch doesn`t work either

**Comment by gmpreussner** [comment]
Please try this: https://answers.unrealengine.com/questions/399361/movie-playback-issue-in-411-standalone-vs-new-edit.html

**Comment by gmpreussner** [comment]
You're probably trying to play the movie while it is still opening. Please try this: https://answers.unrealengine.com/questions/449033/media-player-not-working-on-packaged-project-in-41.html

Also, in 4.13 the MediaPlayer asset will have a PlayOnOpen option, so you only need to call OpenUrl in your Blueprint.
