### ISSUE TITLE
Include wrong files

### ISSUE THREAD

**Issue by zhouhuirun2015** [ue4plugins/VlcMedia#19]
When compiled in 4.10.2 or 4.12.3, it warns that missing files below:
1. Runtime/Media/Public/IMediaOptions.h
2. Runtime/Media/Public/IMediaAudioSink.h
3. Runtime/MediaAssets/Public/FileMediaSource.h

Cannot find these files in engine source dir.

**Comment by bourreP** [comment]
Hi,

In the README.md:

> Make sure to pull the Tag that matches your Unreal Engine version. If you sync to Master the code may not compile, because it may depend on Engine changes that are not yet available in the UE4 Master branch.

Have you use the good tag (not the master branch)?

**Comment by zhouhuirun2015** [comment]
Still cannot find these files in 4.12.0-preview-1 ~ 4.12.0-preview-5

**Comment by gmpreussner** [comment]
Please sync to the VlcMedia 4.12 tag, not Master

**Comment by zhouhuirun2015** [comment]
Ok, Thanks.
