### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by Liberte78** [ue4plugins/VlcMedia#21]
Hi,
I'm trying to implement VLCMedia plugin in Unreal 4.13 preview but without success. Is current version comatible with 4.13 preview?

And I'm courios but are you  also an UE4 engine developer?  :)

**Comment by KhArtNJava** [comment]
Hello.
For what you build this plugin? )

**Comment by Liberte78** [comment]
I'm not sure if I understand your question (english is not my native). Are you asking why I would like to implement RTSP media stream in my project?

**Comment by KhArtNJava** [comment]
I would like to recommend to use WMF Media Player, if you use H264 streaming... But, if you use RTSP...

**Comment by gmpreussner** [comment]
@Liberte78 the Master branch of this repository is compatible with 4.13-preview. I will tag it as 4.13 once the final 4.13 release is out.
