### ISSUE TITLE
[4.13] .wav files no longer import as Sound Waves if VlcMedia plugin is enabled.

### ISSUE THREAD

**Issue by Poeticode** [ue4plugins/VlcMedia#23]
As the title suggests, any .wav files that I try to import into my content browser show up as File Media Source assets instead of Sound Wave assets. They correctly import as Sound Wave assets when the VlcMedia plugin is disabled.

**Comment by gmpreussner** [comment]
Yep, this will be fixed in the 4.13.1 compatible release. The commit was https://github.com/ue4plugins/VlcMedia/commit/fa7952699a3f2831cf1c7641db06ceb837accd71
