### ISSUE TITLE
Can't make it play rtsp stream

### ISSUE THREAD

**Issue by heavior** [ue4plugins/VlcMedia#26]
More like a question, not an issue: I just can't make it work.

I have StreamMediaSource with this url: rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4

Vlc plays this link just fine, but Unreal shows an error:

LogMediaAssets:Error: Could not find a native player for rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4

All other mediaplayer plugins except VlcMedia are disabled.

What am I doing wrong? 
Do you have some example working project?

**Comment by gmpreussner** [comment]
That URL plays fine for me. It looks like your VlcMedia plug-in is not actually loading. Please check your log file.
