### ISSUE TITLE
UE4.14 Failed to play RTSP stream

### ISSUE THREAD

**Issue by judyzhoubaby** [ue4plugins/VlcMedia#29]
I'm trying to play the rtsp stream in UE4 and have some problems.
Here is the log:

LogVlcMedia: Failed to connect with rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4
LogVlcMedia:Error: connection timed out
LogVlcMedia: Failed to connect to RTSP server mpv.cdn3.bigcdn.com:554
LogVlcMedia:Error: Cseq mismatch, got 1, assumed 0
LogVlcMedia:Error: only real/helix rtsp servers supported for now
LogVlcMedia: cannot access rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4
LogVlcMedia: Your input can't be opened
LogVlcMedia: VLC is unable to open the MRL 'rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4'. Check the log for details.

**Comment by judyzhoubaby** [comment]
I install the vlc player and solve the problem.

**Comment by gmpreussner** [comment]
Out of curiosity, what platform are you on?

**Comment by araratm** [comment]
Hi there,

I'm using vlc player to stream rtsp, but the latency is so big, it updates frames every second and sometimes it takes a little bit less. In general it has high latency rate. 
Can anybody help me? Is there an option for that? Or is there specific video sizes?

**Comment by gmpreussner** [comment]
@araratm could it be the server or maybe your internet connection? I've streamed RTSP from various internet sources without problems. Sometimes it takes a while to connect and buffer, but once it plays, there are no frame rate issues.

**Comment by gmpreussner** [comment]
Responded in other issue.
