### ISSUE TITLE
EU crashed on AVI file

### ISSUE THREAD

**Issue by KhArtNJava** [ue4plugins/VlcMedia#3]
Hi.

I pointed MediaPlayer URL to AVI file and UE crashed:

MachineId:8B6EA9114D13098AE8CC5C8620670CBE
EpicAccountId:f025becc996c43498a11ed55681e4f0c

Access violation - code c0000005 (first/second chance not available)

""

libvlccore
libvlc
UE4Editor_VlcMedia!FVlcMediaPlayer::HandleTicker() [c:\temp\unrealengine\unrealengine\engine\plugins\media\vlcmedia\source\vlcmedia\private\player\vlcmediaplayer.cpp:440]
UE4Editor_Core!FTicker::Tick() [c:\temp\unrealengine\unrealengine\engine\source\runtime\core\private\containers\ticker.cpp:107]
UE4Editor!FEngineLoop::Tick() [c:\temp\unrealengine\unrealengine\engine\source\runtime\launch\private\launchengineloop.cpp:2510]
UE4Editor!GuardedMain() [c:\temp\unrealengine\unrealengine\engine\source\runtime\launch\private\launch.cpp:142]
UE4Editor!GuardedMainWrapper() [c:\temp\unrealengine\unrealengine\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [c:\temp\unrealengine\unrealengine\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]

https://answers.unrealengine.com/storage/attachments/47999-logs.zip

**Comment by KhArtNJava** [comment]
I hope, that it https://github.com/ue4plugins/VlcMedia/pull/5 can helpful.

**Comment by gmpreussner** [comment]
Good catch, thanks! Fixed via https://github.com/ue4plugins/VlcMedia/commit/143d0f85ca25dad3e3748fa84dc3fcc5531bec20
