### ISSUE TITLE
UE 4.15.1 Build Failed.

### ISSUE THREAD

**Issue by Ozymandias1** [ue4plugins/VlcMedia#30]
I follow this steps.

1. download VlcMedia (https://github.com/ue4plugins/VlcMedia/releases/tag/4.15)
2. Copy the file and folders into my Test C++ Game Project.
3. Generate Visual Studio project files.
4. Open Visual Studio (I use Visual Studio Community 2015) and Build.
5. and I see error(see below picture)
![image](https://cloud.githubusercontent.com/assets/25314753/24862484/be817d4a-1e37-11e7-9dd1-d462045266db.png)

so, how can i fix it?

is this not supported on Unreal Engine 4.15.1?

best regards.

**Comment by KhArtNJava** [comment]
Hi.
Just ignore this error...

**Comment by Ozymandias1** [comment]
thanks for reply.

I try to ignore error. but i can't.

if i ignore this error and open unreal engine project file, then i see this error.
![image](https://cloud.githubusercontent.com/assets/25314753/24889864/8cd4f41e-1ea7-11e7-9da1-18d1f46e4ada.png)
in this step, i click yes button, then this error appeared.

![image](https://cloud.githubusercontent.com/assets/25314753/24889756/d82d4278-1ea6-11e7-8bea-3d4211218ce9.png)

is this possible to build error by 2-byte character system? (ue4 or os).

i use korean language.

best regards.

**Comment by gmpreussner** [comment]
Sorry, this was a bug in 4.15. I missed a UBT change in 4.15 that prevents the plug-in from compiling as a project plug-in. Please clone the plug-in into /Engine/Plugins instead. Alternatively, you can also add the following line to all three *.Build.cs files:

 `PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;`

**Comment by fuliangjun1002** [comment]
@gmpreussner 
hello,I use VlcMedia in UE 4.15 , it build failed too . And then i clone the plug-in into /Engine/Plugins instead , i can build succeeded , But when i using vlc player to stream rtsp videos it was crashed.
    
![crash](https://user-images.githubusercontent.com/20501414/30470822-e220135c-9a28-11e7-8b5b-f85dc3b4bfbe.png)

    here is the crash information:

LoginId:a4845d974af43a2ff84c8ea3ec6872bc
EpicAccountId:

Access violation - code c0000005 (first/second chance not available)

UE4Editor_Core!rml::internal::LargeObjectCacheImpl<rml::internal::LargeObjectCacheProps<8192,8388608,8192,2,2,16> >::CacheBin::cleanToThreshold()
UE4Editor_Core!rml::internal::LargeObjectCacheImpl<rml::internal::LargeObjectCacheProps<8192,8388608,8192,2,2,16> >::CacheBin::CacheBinFunctor::operator()()
UE4Editor_Core!rml::internal::LargeObjectCacheImpl<rml::internal::LargeObjectCacheProps<8192,8388608,8192,2,2,16> >::CacheBin::cleanToThreshold()
UE4Editor_Core!rml::internal::LargeObjectCacheImpl<rml::internal::LargeObjectCacheProps<8192,8388608,8192,2,2,16> >::regularCleanup()
UE4Editor_Core!rml::internal::LargeObjectCache::doCleanup()
UE4Editor_Core!rml::internal::LargeObjectCache::putList()
UE4Editor_Core!rml::internal::LocalLOCImpl<8,32>::put()
UE4Editor_Core!rml::internal::MemoryPool::putToLLOCache()
UE4Editor_Core!FMallocTBB::Free() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\hal\malloctbb.cpp:133]
UE4Editor_Core!FMemory::Free() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\public\hal\fmemory.inl:52]
UE4Editor_Core!FStatPacketArray::Empty() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\stats\statsdata.cpp:617]
UE4Editor_Core!TSet<TPair<__int64,FStatPacketArray>,TDefaultMapKeyFuncs<__int64,FStatPacketArray,0>,FDefaultSetAllocator>::Remove() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\public\containers\set.h:613]
UE4Editor_Core!FStatsThreadState::AddToHistoryAndEmpty() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\stats\statsdata.cpp:1005]
UE4Editor_Core!FStatsThread::Tick() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\stats\stats2.cpp:934]
UE4Editor_Core!FStatsThread::StatMessage() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\stats\stats2.cpp:961]
UE4Editor_Core!TGraphTask<FStatMessagesTask>::ExecuteTask() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\public\async\taskgraphinterfaces.h:883]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\async\taskgraph.cpp:954]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\async\taskgraph.cpp:701]
UE4Editor_Core!FStatsThread::Run() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\stats\stats2.cpp:863]
UE4Editor_Core!FRunnableThreadWin::Run() [d:\program files\epic games\ue_4.15_build\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:76]


How can i fixed it? ( T.T )
