### ISSUE TITLE
Having problems building this with UE4.14

### ISSUE THREAD

**Issue by pansit** [ue4plugins/VlcMedia#32]
I'm trying to use this as a project plugin. When I try to generate project files I get errors saying that "Plugins\VlcMedia\Source\VlcMedia\VlcMedia.Build.cs(11,19), The Type or Namespacename 'ReadOnlyTargetRules' could not be found for all three *.Build.cs.

Googling the problem revealed that changing the line `public VlcMedia(ReadOnlyTargetRules Target) : base(Target)` to `public VlcMedia(TargetInfo Target)` might help. After doing that the BT generates the files just fine, but when I try to start the Editor I get prompted that `UE4Editor-VlcMedia.dll`, `UE4Editor-VlcMediaEditor.dll` and `UE4Editor-VlcMediaFactory.dll` were built with a different engine and if I would like to rebuild them. After confirming I get the error that the project couldnt be compiled and that I should try compiling it manually.

When trying to compile the project in VS2015 I get this error: "[...]VlcMedia\Source\VlcMediaFactory\Private\VlcMediaFactoryModule.cpp' is trying to include the file 'CoreMinimal.h' as the precompiled header, but that file could not be located in any of the module's include search paths."

So right now I dont feel experienced enough to continue troubleshooting on my own since I assume the code of the plugin to be correct. Can someone tell me what I am missing? It would be much appreciated.

Just fyi, I installed vlc-3.0.0-20170411-1225 nightly but I dont feel like that has anything to do with my issue anyway.

**Comment by gmpreussner** [comment]
Did you pull the [4.14 tag of VlcMedia](https://github.com/ue4plugins/VlcMedia/tree/4.14) into your project? The code at head revision requires 4.16 and will not work with 4.14. Make sure you get the right version.

**Comment by gmpreussner** [comment]
Also, you don't need to install VLC on Windows and macOS. All required libraries are included.

**Comment by pansit** [comment]
I tried again with the code you linked and it worked. Thank you. Consider the issue resolved.
