### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by PetroRandy** [ue4plugins/VlcMedia#40]
I added this plugin to an existing C++ UE4 project on 4.16.3. The C++ project compiles fine without the plugin. I added the plugin to the project's Plugin folder and remade the project files. With the plugin it's not picking up several header files -
Cannot open include file: "IMediaTextureSample.h": No such file or directory.

Are these files that are supposed to be in your project or UE4 files? How do I resolve this? I have the UE4 source code and I don't see this header on my hard drive. A google search just returns one other media plugin. I don't see the header file in any Epic Games repositories. Thanks!

**Comment by gmpreussner** [comment]
You have to pull the VlcMedia tag that corresponds to your version of UE4. If your UE4 version is 4.16.3 then you need to pull the [4.16 tag](https://github.com/ue4plugins/VlcMedia/tree/4.16). You can also download the [4.16 release](https://github.com/ue4plugins/VlcMedia/releases/tag/4.16) ZIP file.

**Comment by PetroRandy** [comment]
Thanks! I'll give that a shot.

**Comment by PetroRandy** [comment]
Using the 4.16 branch works. I grabbed this plugin as we want to play .webm VP9 encoded videos in Unreal and VLC supports it. Now that I have the plugin building, the plugin isn't opening that file extension nor is it playing a VP9 encoded .mp4. In the editor it's showing the plugin as enabled. I see that in VlcMediaFactoryModule.cpp that you're adding support for that extension here - SupportedFileExtensions.Add(TEXT("webm"));

Do you have any guidance on how to proceed from here? Thanks!

**Comment by gmpreussner** [comment]
I don't know if the 4.16 version supports your video format. Can you send me the video? Then I can try to repro it in 4.18. Thanks!

**Comment by gmpreussner** [comment]
Actually, please open a new issue for the file format problems, so I can close this one, thanks!

**Comment by PetroRandy** [comment]
Will do.
