### ISSUE TITLE
.webm file extension not recognized

### ISSUE THREAD

**Issue by PetroRandy** [ue4plugins/VlcMedia#42]
Version: Unreal 4.16.3, Windows

The VLC plugin doesn't seem to recognize files ending in .webm in the editor.
Steps:
1. Put video file https://base-n.de/webm/out9.webm in Content/Movies
2. Navigate to Content/Movies in editor.
3. Click import and navigate to the file, notice it doesn't appear in the file selector.
4. Type the file name out9.webm in file selector

Results:
Failed to import out9.webm. Unknown extension.

Note: If you rename out9.webm to out9.mp4 then the VLC plugin will pick it up and play the VP9 video. The plugin has the "webm" extension specified in VlcMediaFactoryModule.cpp - SupportedFileExtensions.Add(TEXT("webm"));

**Comment by gmpreussner** [comment]
Should be fixed now, thanks!
