### ISSUE TITLE
Linux  UE4.17 Could not find file Module.VlcMediaFactory.gen.cpp

### ISSUE THREAD

**Issue by TON14** [ue4plugins/VlcMedia#43]
View log file
[log.txt](https://github.com/ue4plugins/VlcMedia/files/1368361/log.txt)

**Comment by gmpreussner** [comment]
Linux is not officially supported yet. Please refer to the following thread for details on how to make it work, thanks! https://github.com/ue4plugins/VlcMedia/issues/17
