### ISSUE TITLE
What is the "\ThirdParty\vlc\win32" folder used for ?

### ISSUE THREAD

**Issue by fuliangjun1002** [ue4plugins/VlcMedia#44]
Hello ,
I have trouble in running this plugin in 4.17 , I heard that we can use the 32-bit plugin in 64-bit computer , really ?  Now that the unreal engine can only run in 64-bit computer, what's the "\ThirdParty\vlc\Win32" folder used for ? How can i use the 32-bit plugin ?

![default](https://user-images.githubusercontent.com/20501414/31722882-db0151a8-b44f-11e7-83c1-abec52fd23cc.JPG)

thx !

**Comment by gmpreussner** [comment]
While the Editor requires Win64, we still support the Win32 target for games. We did drop support for XP and Vista not too long ago. The purpose of the /Win32/ folder is to provide LibVLC binaries for Win32 builds. If you don't ship on Win32, you can delete it.
