### ISSUE TITLE
Many LogVlcMedia:Error

### ISSUE THREAD

**Issue by KhArtNJava** [ue4plugins/VlcMedia#6]
Hi, Gerke Max Preussner.

I found new bug.

Repro video: https://youtu.be/cRIqySmf1W0
First video file: https://goo.gl/bGFgDB
Video in second step: http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4
Log: https://goo.gl/wS5s6P

Thank you!

**Comment by gmpreussner** [comment]
Finally had a chance to look into this - unfortunately, your links are no longer working.

What exactly is the error here? Are you referring to all the log spew that VLC generates? I don't think there is a way to disable that right now, unfortunately. The APIs for setting log verbosity seem to have been deprecated. I couldn't find a workaround for this.

**Comment by gmpreussner** [comment]
Also, the LogVlcMedia:Error: lines in the log are simply passed through from libvlc. Those are errors generated by libvlc itself during playback. I tried the bunny video you linked above, and I don't know really know what those errors mean. They seem to be internal.

**Comment by gmpreussner** [comment]
I haven't found a way to suppress the debug log. I can filter the verbosity of the UE4 log, but libvlc still writes a bunch of spew into stdout. If you find a solution, please let me know.

**Comment by KhArtNJava** [comment]
Hi!
I've Google'ed and found some solution - hope, that it will be helpful (I didn't test them):
1)
You can remove that output by setting the environement variable VLC_VERBOSE to 0 or -1
https://forum.videolan.org/viewtopic.php?t=47003#p153922

2) 
child_process.spawn('vlc',['-I dummy','--dummy-quiet'])
child_process.spawn('vlc',['-I rc','--rc-quiet'])

VLC has a command line option to suppress this window --*-quiet where * is the interface.

e.g. For the dummy interface, use

child_process.spawn('vlc',['-I dummy','--dummy-quiet']) For the rc interface, use

child_process.spawn('vlc',['-I rc','--rc-quiet'])

answered Jun 13 '11 at 14:12 Adam M-W
at least on my system, VLC now sends its messages to stdError, so this is the channel which needs to be monitored.

My interface is with Qt , QtProcess and these are the options that worked for me.

Using MergedChannels and reading stdOut.

m_proc->setProcessChannelMode(QProcess::MergedChannels);
connect (m_proc,SIGNAL(readyReadStandardOutput()),
           this, SLOT(readyRead()));

void ReDirVLC::readyRead(){
    if (!m_proc) return;
    qDebug()<<m_proc->readAllStandardOutput() << endl;
}
Using SeparateChannels and reading stdError

m_proc->setProcessChannelMode(QProcess::SeparateChannels);
connect (m_proc,SIGNAL(readyReadStandardError()),
           this, SLOT(readyRead()));

void ReDirVLC::readyRead(){
    if (!m_proc) return;
    qDebug()<<m_proc->readAllStandardError() << endl;
}

http://stackoverflow.com/questions/6001034/how-to-prevent-console-from-being-displayed-when-using-vlcs-dummy-interface

**Comment by gmpreussner** [comment]
Yeah, I found the environment variable hack as well, but that's not really a good option. Neither --quiet nor dummy-quiet seemed to do the track. That being said, the debug log spam is actually only printed in Visual Studio, but not written to the UE log file, so I'd consider this less of a problem.

I added settings for the plug-in that you can configure in Edit -> Project Settings -> Plugins -> VLC Media to enable/disable the VLC log output altogether. For more detailed filtering, use the existing "LogVlcMedia" log category to enable/suppress VLC log messages in the Engine.ini.
