### ISSUE TITLE
HEY ASSHOLES SUPPORT YOUR WORK AND UPDATE YOUR SHIT!

### ISSUE THREAD

**Issue by RacerXx** [ue4plugins/VlcMedia#72]
HEY ASSHOLES SUPPORT YOUR WORK AND UPDATE YOUR SHIT! You got alot of questions here take the time to fucking answer some of them DICK!

**Comment by MylesAdams** [comment]
@RacerXx These people who made this did it for free and don't owe you or anyone anything. Why don't you put some time in and try to update it yourself and put in a pull request?

**Comment by RacerXx** [comment]
o
oh you mean like the 2 other unanswered pull requests? Yeah that works. I just hate stupid. I got this working in ue4 4.25 but im not sharing because nobody else is. So live with that. Like I said update you shit! Laters unsubscribing
