### ISSUE TITLE
Plugin 'VlcMedia' failed to load because module 'VlcMedia' could not be found.

### ISSUE THREAD

**Issue by KhArtNJava** [ue4plugins/VlcMedia#8]
I've placed Plugin to the Plugins dir of my test UE 4.9 project and after that project can't be started.
---------------------------
Message
---------------------------
Plugin 'VlcMedia' failed to load because module 'VlcMedia' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
---------------------------
ОК   
---------------------------

http://s6.postimg.org/hj3kpmtf5/screenshot_241.png
http://pastebin.com/3N9zWemY

**Comment by gmpreussner** [comment]
I cannot repro this. Did you recompile the project?
