### ISSUE TITLE
Play rtsp stream Failed on 4.26,Any Help?

### ISSUE THREAD

**Issue by ShawnChiang886** [ue4plugins/VlcMedia#84]
My stream Url is like this rtsp://admin:xxxxxx@192.168.66.41:80/cam/realmonitor?channel=1&subtype=0,and when I play on ue4,there is no picture in the view ,and show errors blow:
LogVlcMedia: Error: mmdevice: cannot initialize COM (error 0x80010106)
LogVlcMedia: Warning: main: Password in a URI is DEPRECATED
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: video format setup failure (no pictures)
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output
LogVlcMedia: Error: vmem: missing lock callback
LogVlcMedia: Error: main: video output creation failed
LogVlcMedia: Error: main: failed to create video output

**Comment by fpibbs** [comment]
same here unfortunately, Unreal 5.0.3....

**Comment by JSCOP** [comment]
Did you solve this problem?
