### ISSUE TITLE
Project crashed

### ISSUE THREAD

**Issue by KhArtNJava** [ue4plugins/VlcMedia#9]
MachineId:8B6EA9114D13098AE8CC5C8620670CBE
EpicAccountId:f025becc996c43498a11ed55681e4f0c

Unknown exception - code 00000001 (first/second chance not available)

"Assertion failed: IsValid() [File:D:\BuildFarm\buildmachine_++depot+UE4-Releases+4.9\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 708] 

UE4Editor_Core!FDebug::AssertFailed() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\private\misc\outputdevice.cpp:354]
UE4Editor_PropertyEditor!SPropertyNameWidget::Construct() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\propertyeditorhelpers.cpp:58]
UE4Editor_PropertyEditor!TDecl<SPropertyNameWidget,RequiredArgs::T1RequiredArgs<TSharedPtr<FPropertyEditor,0> const & __ptr64> >::operator<<=() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slatecore\public\widgets\declarativesyntaxsupport.h:1330]
UE4Editor_PropertyEditor!FDetailPropertyRow::MakeNameWidget() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\detailpropertyrow.cpp:372]
UE4Editor_PropertyEditor!FDetailPropertyRow::GetDefaultWidgets() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\detailpropertyrow.cpp:135]
UE4Editor_TextureEditor!FTextureDetails::CustomizeDetails() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\textureeditor\private\customizations\texturedetailscustomization.cpp:67]
UE4Editor_PropertyEditor!SDetailsViewBase::QueryCustomDetailLayout() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\sdetailsviewbase.cpp:607]
UE4Editor_PropertyEditor!SDetailsViewBase::UpdatePropertyMap() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\sdetailsviewbase.cpp:1191]
UE4Editor_PropertyEditor!SDetailsView::PostSetObject() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\sdetailsview.cpp:638]
UE4Editor_PropertyEditor!SDetailsView::SetObjectArrayPrivate() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\sdetailsview.cpp:462]
UE4Editor_PropertyEditor!SDetailsView::SetObjects() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\sdetailsview.cpp:322]
UE4Editor_PropertyEditor!SDetailsView::SetObject() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\propertyeditor\private\sdetailsview.cpp:329]
UE4Editor_TextureEditor!FTextureEditorToolkit::BuildTexturePropertiesWidget() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\textureeditor\private\textureeditortoolkit.cpp:604]
UE4Editor_TextureEditor!FTextureEditorToolkit::CreateInternalWidgets() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\textureeditor\private\textureeditortoolkit.cpp:724]
UE4Editor_TextureEditor!FTextureEditorToolkit::InitTextureEditor() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\textureeditor\private\textureeditortoolkit.cpp:162]
UE4Editor_TextureEditor!FTextureEditorModule::CreateTextureEditor() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\textureeditor\private\textureeditormodule.cpp:39]
UE4Editor_MediaPlayerEditor!FMediaTextureActions::OpenAssetEditor()
UE4Editor_UnrealEd!FAssetEditorManager::OpenEditorForAsset() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\unrealed\private\toolkits\asseteditormanager.cpp:303]
UE4Editor_MediaPlayerEditor!FAssetTypeActions_Base::AssetsActivated()
UE4Editor_ContentBrowser!SContentBrowser::OnAssetsActivated() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\contentbrowser\private\scontentbrowser.cpp:1757]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SContentBrowser,0,TTypeWrapper<void> __cdecl(TArray<FAssetData,FDefaultAllocator> const & __ptr64,enum EAssetTypeActivationMethod::Type)>::Execute() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:282]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SContentBrowser,0,void __cdecl(TArray<FAssetData,FDefaultAllocator> const & __ptr64,enum EAssetTypeActivationMethod::Type)>::ExecuteIfSafe() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:388]
UE4Editor_ContentBrowser!SAssetView::OnListMouseButtonDoubleClick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\editor\contentbrowser\private\sassetview.cpp:3284]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SAssetView,0,TTypeWrapper<void> __cdecl(TSharedPtr<FAssetViewItem,0>)>::Execute() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:282]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SAssetView,0,void __cdecl(TSharedPtr<FAssetViewItem,0>)>::ExecuteIfSafe() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\public\delegates\delegateinstancesimpl_variadics.inl:388]
UE4Editor_ContentBrowser!TBaseDelegate<void,TSharedPtr<FAssetViewItem,0> >::ExecuteIfBound() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\public\delegates\delegatesignatureimpl_variadics.inl:482]
UE4Editor_ContentBrowser!SListView<TSharedPtr<FAssetViewItem,0> >::Private_OnItemDoubleClicked() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slate\public\widgets\views\slistview.h:689]
UE4Editor_ContentBrowser!STableRow<TSharedPtr<FAssetViewItem,0> >::OnMouseButtonDoubleClick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slate\public\widgets\views\stablerow.h:261]
UE4Editor_Slate!<lambda_58ede244782f1e594383d45514e1d7c8>::operator()() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4597]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,<lambda_58ede244782f1e594383d45514e1d7c8> >() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:214]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonDoubleClickEvent() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4598]
UE4Editor_Slate!FSlateApplication::OnMouseDoubleClick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:4578]
UE4Editor_Core!FWindowsApplication::ProcessDeferredMessage() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\private\windows\windowsapplication.cpp:1345]
UE4Editor_Core!FWindowsApplication::DeferMessage() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\private\windows\windowsapplication.cpp:1708]
UE4Editor_Core!FWindowsApplication::ProcessMessage() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\private\windows\windowsapplication.cpp:706]
UE4Editor_Core!FWindowsApplication::AppWndProc() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\private\windows\windowsapplication.cpp:628]
user32
user32
UE4Editor_Core!FWindowsPlatformMisc::PumpMessages() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\core\private\windows\windowsplatformmisc.cpp:792]
UE4Editor!FEngineLoop::Tick() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\launch\private\launchengineloop.cpp:2376]
UE4Editor!GuardedMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\launch\private\launch.cpp:142]
UE4Editor!GuardedMainWrapper() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.9\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]

Log:

LogInit:Display: RandInit(-1841255625) SRandInit(-1841255624).
LogTaskGraph: Started task graph with 4 named threads and 5 total threads.
LogStats: Stats thread started at 0.123478
LogInit: Version: 4.9.0-2641355+++depot+UE4-Releases+4.9
LogInit: API Version: 2641355
LogInit: Compiled (64-bit): Aug  1 2015 02:28:28
LogInit: Compiled with Visual C++: 18.00.21005.01
LogInit: Build Configuration: Development
LogInit: Branch Name: ++depot+UE4-Releases+4.9
LogInit: Command line:  
LogInit: Base directory: C:/Program Files/Epic Games/4.9/Engine/Binaries/Win64/
LogInit: Rocket: 1
LogInit: Using libcurl 7.41.0
LogInit:  - built for x86_64-pc-win32
LogInit:  - supports SSL with WinSSL
LogInit:  - other features:
LogInit:      CURL_VERSION_SSL
LogInit:      CURL_VERSION_IPV6
LogInit:      CURL_VERSION_ASYNCHDNS
LogInit:      CURL_VERSION_LARGEFILE
LogInit:      CURL_VERSION_IDN
LogInit:  CurlRequestOptions (configurable via config and command line):
LogInit:  - bVerifyPeer = true  - Libcurl will verify peer certificate
LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
LogInit:  - CertBundlePath = nullptr  - Libcurl will use whatever was configured at build time.
LogInit: Presizing for 0 objects not considered by GC, pre-allocating 0 bytes.
LogInit: Object subsystem initialized
LogInit: Selected Device Profile: [Windows]
LogInit: Applying CVar settings loaded from the selected device profile: [Windows]
LogInit: Computer: ARTKHUSNUTDINOV
LogInit: User: ArtUrlWWW
LogInit: CPU Page size=4096, Cores=2
LogInit: High frequency timer resolution =2.338338 MHz
LogMemory: Memory total: Physical=7.8GB (8GB approx)
LogMemory: Platform Memory Stats for Windows
LogMemory: Process Physical Memory: 53.65 MB used, 53.65 MB peak
LogMemory: Process Virtual Memory: 55.49 MB used, 55.49 MB peak
LogMemory: Physical Memory: 6175.62 MB used, 7962.15 MB total
LogMemory: Virtual Memory: 348.50 MB used, 134217728.00 MB total
LogTextLocalizationManager: No translations for ('ru-RU') exist, falling back to 'en' for localization and internationalization data.
LogInput:Warning: Category Steam already has menu display info that is being replaced.
LogInput:Warning: Category Steam already has menu display info that is being replaced.
LogD3D11RHI: Found D3D11 adapter 0: NVIDIA GeForce GT 740M        (Feature Level 11_0)
LogD3D11RHI: Adapter has 1994MB of dedicated video memory, 0MB of dedicated system memory, and 2048MB of shared system memory, 1 output[s]
LogD3D11RHI: Found D3D11 adapter 1: NVIDIA GeForce GT 740M        (Feature Level 11_0)
LogD3D11RHI: Adapter has 1994MB of dedicated video memory, 0MB of dedicated system memory, and 2048MB of shared system memory, 0 output[s]
LogD3D11RHI: Found D3D11 adapter 2: NVIDIA GeForce GT 740M        (Feature Level 11_0)
LogD3D11RHI: Adapter has 1994MB of dedicated video memory, 0MB of dedicated system memory, and 2048MB of shared system memory, 0 output[s]
LogD3D11RHI: Chosen D3D11 Adapter Id = 0
LogD3D11RHI: !Direct3DDevice
LogRHI: Texture pool is 1361 MB (70% of 1945 MB)
LogD3D11RHI: Async texture creation enabled
LogShaderCompilers: Cleaned the shader compiler working directory '../../../../../../Users/ArtUrlWWW/Documents/Unreal Projects/MediaPlayerTest/Intermediate/Shaders/WorkingDirectory/4728/'.
LogShaderCompilers:Display: Using Local Shader Compiler.
LogContentStreaming: Texture pool size is 0.000000MB
LogTemp:Display: Loaded TP AllDesktopTargetPlatform
LogTemp:Display: Loaded TP WindowsClientTargetPlatform
LogTemp:Display: Loaded TP WindowsNoEditorTargetPlatform
LogTemp:Display: Loaded TP WindowsServerTargetPlatform
LogTemp:Display: Loaded TP WindowsTargetPlatform
LogTemp:Display: Loaded TP AndroidTargetPlatform
LogTemp:Display: Loaded TP Android_ASTCTargetPlatform
LogTemp:Display: Loaded TP Android_ATCTargetPlatform
LogTemp:Display: Loaded TP Android_DXTTargetPlatform
LogTemp:Display: Loaded TP Android_ETC1TargetPlatform
LogTemp:Display: Loaded TP Android_ETC2TargetPlatform
LogTemp:Display: Loaded TP Android_PVRTCTargetPlatform
LogTemp:Display: Loaded TP HTML5TargetPlatform
LogTemp:Display: Loaded TP IOSTargetPlatform
LogTemp:Display: Loaded TP LinuxNoEditorTargetPlatform
LogTemp:Display: Loaded TP LinuxServerTargetPlatform
LogTemp:Display: Loaded TP LinuxTargetPlatform

**Comment by gmpreussner** [comment]
I think this was fixed in https://github.com/EpicGames/UnrealEngine/commit/d97aceb2ff1f19a0de9ad926e939e342d57e314b
